services:
  worker_dispatcher:
    build:
      context: ./src
      dockerfile: Dockerfile
    container_name: worker-dispatcher
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - net
    environment:
      - ENVIRONMENT=production      
networks:
  net:
    external: true